package rjlink.server.db

import org.jetbrains.exposed.v1.core.Table

/** User nicknames known to the system. Primary identity. */
object UsersTable : Table("users") {
    val nick = text("nick")
    val createdAt = long("created_at")

    override val primaryKey = PrimaryKey(nick)
}

/** Persistent mapping between a nickname and the Telegram chat bound to it. */
object TgBindingsTable : Table("tg_bindings") {
    val nick = text("nick")
    val tgChatId = long("tg_chat_id")

    override val primaryKey = PrimaryKey(nick)
}

/** Persistent, deterministic per-chat codes generated by [rjlink.tgbot.server.TgCodeGenerator]. */
object TgCodesTable : Table("tg_codes") {
    val tgChatId = long("tg_chat_id")
    val code = text("code").uniqueIndex()

    override val primaryKey = PrimaryKey(tgChatId)
}

/** Persistent ban list, written by the admin module. */
object BansTable : Table("bans") {
    val nick = text("nick")
    val reason = text("reason")
    val bannedAt = long("banned_at")
    val bannedBy = text("banned_by").nullable()

    override val primaryKey = PrimaryKey(nick)
}
